spring:
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  datasource:
    postgres:
      jdbc-url: jdbc:postgresql://localhost:5432/cloud_db
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver

    # Source: IBM i (AS/400)
    as400:
      jdbc-url: jdbc:as400://PUB400.COM;prompt=false;naming=system;libraries=*LIBL;
      username: SHYUDI08
      password: Yudi@0800
      driver-class-name: com.ibm.as400.access.AS400JDBCDriver
      maximum-pool-size: 5
      connection-test-query: SELECT 1 FROM SYSIBM.SYSDUMMY1
